name: Update Google Slides Menu

on:
  workflow_dispatch:

  schedule:
    - cron: '0 7 1 * *'   # 1st of every month at 07:00 UTC

jobs:
  update_slide:
    runs-on: ubuntu-latest

    steps:
      - name: Build iOS Action
        uses: sparkfabrik/ios-build-action@v2.3.2
